function [ RefFile, DSFiles ] = GetCSVs( )
% This function retrieves reference and error output information from 
% .csv files generated by DREAM.3D
 
[filename,pathname]=uigetfile('*.csv','Choose Original Microstructure Stats File');
RefFile = char(strcat(pathname,filename));
 
[filename,pathname]=uigetfile('*.csv','Choose Corresponding Down-Sampled Files','MultiSelect','on');
DSFiles=char(strcat(pathname,filename));
 
end